// <auto-generated />
using Housing.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Housing.Infrastructure.Persistence.Migrations.Sqlite
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230719151152_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.9");

            modelBuilder.Entity("Housing.Domain.Entities.HousingLocationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AvailableUnits")
                        .HasColumnType("INTEGER")
                        .HasColumnName("available_units");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT")
                        .HasColumnName("city");

                    b.Property<bool>("Laundry")
                        .HasColumnType("INTEGER")
                        .HasColumnName("laundry");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Photo")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT")
                        .HasColumnName("photo");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("state");

                    b.Property<bool>("Wifi")
                        .HasColumnType("INTEGER")
                        .HasColumnName("wifi");

                    b.HasKey("Id");

                    b.ToTable("HousingLocations");
                });
#pragma warning restore 612, 618
        }
    }
}
